# Generated by Django 4.0.3 on 2022-03-17 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parc', '0003_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_on'], 'verbose_name': 'Parc'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='address_2',
        ),
        migrations.AddField(
            model_name='location',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='precision',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='location',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='parc'),
        ),
    ]
