# Generated by Django 4.0.3 on 2022-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0005_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Dunkerque', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='parc'),
        ),
    ]
