# Generated by Django 4.0.3 on 2022-03-19 22:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0006_alter_location_city_alter_location_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='parc'),
        ),
    ]
