# Generated by Django 4.0.3 on 2022-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0009_alter_location_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='parc'),
        ),
    ]
