# Generated by Django 4.0.3 on 2022-03-22 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parc', '0010_alter_location_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('IN', 'Contenu inapproprié'), ('IS', 'Insultes_propos choquants'), ('NU', 'Nudité'), ('ER', 'Informations erronées'), ('FA', 'Faux comptes')], default='IN', max_length=2)),
                ('contexte', models.TextField(blank=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('traite', models.BooleanField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abus',
                'ordering': ['-created_on'],
            },
        ),
    ]
