# Generated by Django 4.0.3 on 2022-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0012_rename_student_abus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abus',
            options={'ordering': ['-created_on'], 'verbose_name': 'Abu'},
        ),
        migrations.AddField(
            model_name='abus',
            name='parc_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
