# Generated by Django 4.0.3 on 2022-03-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0013_alter_abus_options_abus_parc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abus',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
