# Generated by Django 4.0.3 on 2022-03-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0014_alter_abus_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abus',
            options={'ordering': ['-date'], 'verbose_name': 'Abu'},
        ),
        migrations.RenameField(
            model_name='abus',
            old_name='created_on',
            new_name='date',
        ),
    ]
