# Generated by Django 4.0.3 on 2022-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0019_alter_location_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
