# Generated by Django 4.0.3 on 2022-03-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0020_location_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='59240', max_length=5),
        ),
    ]
