# Generated by Django 4.0.3 on 2022-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0021_alter_location_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default='59240', max_length=5),
        ),
    ]
